import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "./layouts/SideBar";
import TopBar from "./layouts/TopBar";
import MobileSidebar from "./layouts/MobileSidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="grid lg:grid-cols-[15%_85%]">
                    <div className="h-screen bg-red-50 hidden lg:block">
                        <SideBar />
                    </div>
                    <div className="lg:hidden block">
                        <MobileSidebar/>
                    </div>
                    <div className="min-h-screen bg-gray-100 mt-15 lg:mt-0">
                        <header className="lg:block hidden">
                            <TopBar />
                        </header>
                        <main>
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html >
    );
}
