import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavbarPage from "@/layouts/NavbarPage";
import MobileNavbarPage from "@/layouts/MobileNavbarPage";
import Footer from "@/layouts/Footer";
import { CartProvider } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
        <header>
          <NavbarPage />
          <MobileNavbarPage />
        </header>
        <main className="lg:mt-21 mt-15 lg:min-h-screen">
          
            {children}
          
        </main>
        <footer>
          <Footer />
        </footer>
        </CartProvider>
      </body>
    </html>
  );
}
